name: Examples
options:
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "16.0"
    macOS: "13.0"
packages:
  Pagination:
    path: ..
settings:
  base:
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "6.0"
targets:
  Examples:
    type: application
    platform: iOS
    sources:
      - Swift
      - Shared
    settings:
      base:
        CODE_SIGN_IDENTITY: ""
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        PRODUCT_BUNDLE_IDENTIFIER: com.example.Examples
        SDKROOT: auto
        SUPPORTED_PLATFORMS: iphonesimulator iphoneos macosx
        TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - package: Pagination
  Objc:
    type: application
    platform: iOS
    sources:
      - Objc
      - Shared
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        PRODUCT_BUNDLE_IDENTIFIER: com.example.Objc
        SWIFT_VERSION: "6.0"
        TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - package: Pagination
